# Use an official lightweight Node.js image
FROM node:alpine

# Set the working directory in the Docker container
WORKDIR /app

# Change directory to client before copying files
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code from the client directory
COPY client/ ./

# Build the application
RUN npm run build

# Run the application
CMD ["npm", "start"]

# Expose the port the app runs on
EXPOSE 3000