version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "02294:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: shoaib
      MONGO_INITDB_ROOT_PASSWORD: 1234

volumes:
  mongo-data: